### ISSUE TITLE
labelFormatter overlapping in dygraph 1.1.0

### ISSUE THREAD

**Issue by bthieurmel** [danvk/dygraphs#539]
Trying to update to dygraph 1.1.0, we observe some overlapped x-axis label, particularly in the case of monthly data and label, for some zoom level and wondows size. You can the example below :

dygraphs-1 0 1

![ex-1 0 1](https://cloud.githubusercontent.com/assets/8750326/5940395/d96ce014-a70a-11e4-8d3c-9b51b38b73e4.png)

Now here's what I see with dygraphs 1.1.0:

dygraphs-1 1 0

![ex-1 1 0](https://cloud.githubusercontent.com/assets/8750326/5940415/efe0268a-a70a-11e4-9a73-2e766ce1f45b.png)

The issue seems to be that the default changed to show all four digits of the year however the code that handles tick positioning wasn't updated to reflect this.

**Comment by bthieurmel** [comment]
In fact, it seems to be a font family problem. If we decide to use a custom font-family, like in this example (Arial, sans-serif), the ticker placement can result in some overlapping.

**Comment by danvk** [comment]
If you're using custom fonts, you may need to grab some more space for the x-axis labels using [`axisLabelWidth`][1] and [`pixelsPerLabel`][2].

dygraphs doesn't measure your labels before placing them. Maybe it should, but it doesn't, and that's why you're seeing overlapping labels.

[1]: http://dygraphs.com/options.html#axisLabelWidth
[2]: http://dygraphs.com/options.html#pixelsPerLabel
