### ISSUE TITLE
Is there an "overlayCallback" complement to "underlayCallback"?

### ISSUE THREAD

**Issue by musicist288** [danvk/dygraphs#688]
I'm trying to draw on top of the graph after the data renders. `underlayCallback` draws before the data renders so it is not suitable for my use case. `drawCallback` does the trick initially, but if the user mouses over the graph, or the graph re-renders for some other reason, the pixels drawn in `drawCallback` disappear. 

I made a fiddle to demo the issue: http://jsfiddle.net/fudrh6um/1/

I want the text to render 2's appearance, but the persistence that chart 1 has. Is there any way to do with with the existing API/Options? I've been digging through the docs all day an am struggling to find an answer.

**Comment by danvk** [comment]
Here's an updated version of your fiddle that works using `drawCallback`: http://jsfiddle.net/fudrh6um/2/

The trick is to use `hidden_ctx_` rather than `canvas_ctx_`. The former is the layer on which the chart is drawn. The latter is for interactive elements. The names don't make much sense, but hey, they're not part of the public API.

**Comment by musicist288** [comment]
Thanks! Just what I needed. I'm not worried about it being part of the public API.  I also have a possible I encountered, but I'll open another issue for that.
