### ISSUE TITLE
how to have string values in x-axis

### ISSUE THREAD

**Issue by jithjob** [danvk/dygraphs#820]
I have requirements like plotting a graph for 'salesman wise sales', 'department-wise income ' etc... When I try giving string values in x-axis i am getting errors like below.

> Couldn't parse Ahmed as a date

please help.

**Comment by pshevtsov** [comment]
The values other that `date` or `float` are prohibited for `x-values`. See [Data Format](http://dygraphs.com/data.html). However you may put your `string` values in an `array` and use indexes instead of actual `string` values.

See [`xValueParser`](http://dygraphs.com/options.html#xValueParser), [`valueFormatter`](http://dygraphs.com/options.html#valueFormatter) and [`axisLabelFormatter`](http://dygraphs.com/options.html#axisLabelFormatter) as well.
