### ISSUE TITLE
implement sowPointsCount

### ISSUE THREAD

**Issue by Hadatko** [danvk/dygraphs#899]
Hi,
i was curious if you would accept new feature showPointsCoint.
I have larger data but when they are displayed it doesn't look well and it can take time. 
Currently i implemented locally this showPointsCount variable. 
You can have 100 points but you want show only 10 (depends on zoom). 
So you can put in graph each 10th point (1,11,...,100)
for that purpose i am preparing more arrays in background and depends on zoom i am using concrete array.
a1 = [each 10th]
a2 = [each 5th]
a3 = [each 3th]
a4 = [each 2th]
a5 = [each 1th]

I think something like this could be good feature for dygraphs. What is your opinion.

**Comment by danvk** [comment]
dygraphs does something like this already, check out [`DygraphCanvasRenderer._fastCanvasProxy`][1]. Dropping every 100th point probably isn't a good idea for all data sets since you might lose the min/max. Instead, dygraphs drops points which don't visibly affect either the x- or y-value.

[1]: https://github.com/danvk/dygraphs/blob/aec24511f59ace8681d28cb5d11d04f9f57357b4/src/dygraph-canvas.js#L539-L546

**Comment by Hadatko** [comment]
Well from description of that function i am requesting different thing. I have different x values and i have a lot of them (like 135 000). And i need reduce this amount (to e.g. 2500). These data are from measurement. Missed Y value can be averaged.

**Comment by danvk** [comment]
I'd suggest downsampling your data before handing it off to dygraphs, then.

**Comment by Hadatko** [comment]
Well i am doing it in way i described. But i thought it could be good feature for dygraph itself.
